/* The new checkout calls the existing API. It does not store PII in browser
   storage; the server encrypts order data before writing it to Supabase. */
(() => {
  const form = document.querySelector('#checkoutForm');
  if (!form || !window.GOB_API) return;
  const get = selector => form.querySelector(selector)?.value.trim() || '';
  const phone = () => get('[autocomplete="tel"]').replace(/\D/g, '').replace(/^91/, '');
  const fullName = () => [get('[autocomplete="given-name"]'), get('[autocomplete="family-name"]')].filter(Boolean).join(' ');
  const items = () => cart().map(line => {
    const product = GOB_PRODUCTS[line.id];
    return product && { name: product.name, pack_label: product.tag || '', price: Number(product.price), pack_price: Number(product.price), quantity: Number(line.quantity), qty: Number(line.quantity) };
  }).filter(Boolean);
  const subtotal = () => items().reduce((sum, item) => sum + item.price * item.quantity, 0);
  const method = () => form.querySelector('[name="payment"]:checked')?.value === 'cod' ? 'cod' : 'online';
  const address = () => ['street-address', 'address-line2', 'address-level2', 'address-level1', 'postal-code'].map(name => get(`[autocomplete="${name}"]`)).filter(Boolean).join(', ');
  const reference = () => `GOB-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).slice(2, 6).toUpperCase()}`;
  const valid = () => /^\d{10}$/.test(phone()) && Boolean(fullName()) && /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(get('[autocomplete="email"]')) && /^\d{6}$/.test(get('[autocomplete="postal-code"]')) && Boolean(address()) && items().length;
  const total = () => { const value = subtotal(), count = cartCount(), bulk = count >= 10 ? .15 : count >= 8 ? .12 : count >= 5 ? .08 : count >= 3 ? .05 : 0, coupon = form.querySelector('[name="coupon"]:checked')?.value || '', couponRate = coupon === 'WELCOME15' ? .15 : coupon === 'MEGA20' && value >= 2199 ? .2 : 0, discount = Math.round(value * Math.max(bulk, couponRate)), cod = method() === 'cod' ? 40 : -30; return { value, discount, coupon, grand: Math.max(0, value - discount + cod) }; };
  const result = (html, failed = false) => { const el = document.querySelector('#checkoutSuccess'); if (!el) return; el.classList.add('show'); el.style.background = failed ? '#f9e1da' : '#e4ebdf'; el.innerHTML = html; el.focus(); };
  let captureTimer;
  async function capture() { if (!/^\d{10}$/.test(phone()) || !items().length) return; try { await window.GOB_API.abandonedCart({ phone: phone(), email: get('[autocomplete="email"]'), name: fullName(), items: items(), total: subtotal() }); } catch (_) {} }
  form.addEventListener('input', () => { clearTimeout(captureTimer); captureTimer = setTimeout(capture, 1200); });
  async function save(ref, transactionId = '') { const pricing = total(); return window.GOB_API.saveOrder({ ref, customer_name: fullName(), customer_phone: phone(), customer_email: get('[autocomplete="email"]'), items: items(), subtotal: pricing.value, total_amount: pricing.value, shipping: 0, discount: pricing.discount, grand_total: pricing.grand, payment_method: method() === 'cod' ? 'cod' : 'razorpay', transaction_id: transactionId || null, shipping_address: address(), coupon_code: pricing.coupon || null, packaging: method() === 'cod' ? 40 : 0 }); }
  function razorpayScript() { if (window.Razorpay) return Promise.resolve(); return new Promise((resolve, reject) => { const tag = document.createElement('script'); tag.src = 'https://checkout.razorpay.com/v1/checkout.js'; tag.onload = resolve; tag.onerror = reject; document.head.append(tag); }); }
  async function prepaid(ref, pricing) { const order = await window.GOB_API.createRazorpayOrder({ amount: Math.round(pricing.grand * 100), currency: 'INR', receipt: ref, notes: { ref, customer_name: fullName(), customer_phone: phone(), customer_email: get('[autocomplete="email"]'), items_1: JSON.stringify(items()).slice(0, 1400) } }); await razorpayScript(); return new Promise((resolve, reject) => new window.Razorpay({ key: order.key, amount: order.amount, currency: order.currency, name: 'Game of Bones', description: 'Natural dog treats', order_id: order.order_id, prefill: { name: fullName(), contact: phone(), email: get('[autocomplete="email"]') }, theme: { color: '#bd812a' }, handler: async response => { try { await save(ref, response.razorpay_payment_id); resolve(); } catch (error) { reject(error); } }, modal: { ondismiss: () => reject(new Error('Payment was cancelled.')) } }).open()); }
  form.addEventListener('submit', async event => { event.preventDefault(); if (!valid()) return result('<strong>Checkout needs attention.</strong> Please complete your name, 10-digit mobile number, email, and delivery address.', true); const button = form.querySelector('[type="submit"]'), ref = reference(), pricing = total(); if (button) { button.disabled = true; button.textContent = 'Preparing secure checkout…'; } try { await capture(); await window.GOB_API.orderAttempt({ ref, customer_name: fullName(), customer_phone: phone(), customer_email: get('[autocomplete="email"]'), payment_method: method() === 'cod' ? 'cod' : 'razorpay', subtotal: pricing.value, grand_total: pricing.grand, items: items(), shipping_address: address(), coupon_code: pricing.coupon, coupon_label: pricing.coupon || 'automatic saving' }); if (method() === 'cod') { await save(ref); saveCart([]); updateCart(); result(`<strong>Order ${ref} confirmed.</strong> Pay ₹${pricing.grand.toLocaleString('en-IN')} when it reaches your door.`); } else { await prepaid(ref, pricing); saveCart([]); updateCart(); result(`<strong>Payment received for ${ref}.</strong> We’ll send confirmation to ${get('[autocomplete="email"]')}.`); } } catch (error) { result(`<strong>Checkout could not start.</strong> ${error?.message || 'Please try again or select Cash on Delivery.'}`, true); } finally { if (button) { button.disabled = false; button.textContent = 'Continue to secure payment'; } } });
})();
